/* USER */
export const LOGIN_USER = "LOGIN_USER";

/* JOBS*/
export const RECEIVE_JOBS = "RECEIVE_JOBS";
export const FETCH_JOBS = "FETCH_JOBS";
export const MAX_JOBS = "MAX_JOBS";
export const FILTER_JOBS = "FILTER_JOBS";
export const FILTERED_JOBS = "FILTERED_JOBS";
export const FILTER_JOBS_IN_STATE = "FILTER_JOBS_IN_STATE";
export const CLEAR_FILTERED_JOBS = "CLEAR_FILTERED_JOBS";


/* ORGANIZATIONS */
export const UNIQUE_ORGANIZATIONS = "UNIQUE_ORGANIZATIONS";
export const FILTERED_JOBS_BY_ORGANIZATIONS = "FILTERED_JOBS_BY_ORGANIZATIONS";
export const ADD_SELECTED_ORGANIZATIONS = "ADD_SELECTED_ORGANIZATIONS";
export const JOBS_GETTER = "JOBS_GETTER";
export const INCLUDE_JOB_BY_ORGANIZATION = "INCLUDE_JOB_BY_ORGANIZATION";


/* JOB TYPEs */
export const ADD_SELECTED_JOB_TYPES = "ADD_SELECTED_JOB_TYPES";
export const UNIQUE_JOB_TYPES = "UNIQUE_JOB_TYPES";
export const FILTERED_JOBS_BY_JOB_TYPES = "FILTERED_JOBS_BY_JOB_TYPES";
export const INCLUDE_JOB_BY_JOB_TYPE = "INCLUDE_JOB_BY_JOB_TYPE";
