# Generated by Django 4.0.6 on 2022-08-19 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_job_jobtype_preferredqualifications'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PreferredQualifications',
            new_name='PreferredQualification',
        ),
    ]
