# Generated by Django 4.0.6 on 2022-09-03 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_spotlight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('organization', models.CharField(max_length=50)),
                ('degree', models.CharField(max_length=50)),
                ('jobType', models.CharField(max_length=50)),
                ('dateAdded', models.DateField(blank=True, null=True)),
                ('qualification', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='locations',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='minimumQualifications',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='preferredQualifications',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='description',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='description', to='core.jobs'),
        ),
        migrations.AlterField(
            model_name='location',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='core.jobs'),
        ),
        migrations.AlterField(
            model_name='preferredqualification',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferredQualifications', to='core.jobs'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minimumQualifications', to='core.jobs'),
        ),
    ]
