# Generated by Django 4.0.6 on 2022-08-31 14:48

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_job_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='test',
        ),
        migrations.AddField(
            model_name='job',
            name='qualification',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
