# Generated by Django 4.0.6 on 2022-08-31 15:02

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_job_test_job_qualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='qualification',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
