# Generated by Django 4.0.6 on 2022-08-31 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_job_qualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='qualification',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
