# Generated by Django 4.0.6 on 2022-08-31 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_job_qualification'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Job',
            new_name='Jobs',
        ),
    ]
