# Generated by Django 4.0.6 on 2022-08-31 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_job_jobs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('organization', models.CharField(max_length=50)),
                ('degree', models.CharField(max_length=50)),
                ('jobType', models.CharField(max_length=50)),
                ('locations', models.JSONField(blank=True, null=True)),
                ('minimumQualifications', models.JSONField(blank=True, null=True)),
                ('preferredQualifications', models.JSONField(blank=True, null=True)),
                ('description', models.JSONField(blank=True, null=True)),
                ('dateAdded', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
